default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  schema_search_path: restaurant_api

development:
  <<: *default
  database: restaurant_api_development

test:
  <<: *default
  database: restaurant_api_test

production:
  <<: *default
  database: restaurant_api_production
